event/event/diaries/urls.py
from django.urls import path
from .views import home,album

app_name = 'diaries'

urlpatterns = [
    path('home/album/',album,name="album"),
    path('home/album/<slug:slug_category>',album,name='album'),
    path('home/',home,name='home'),
]

event/event/event/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('diaries.urls',namespace='diaries')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

event/event/diaries/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length=250,unique=True)
    # image = models.ImageField(upload_to="category/%y/%m",blank=True)

    def __str__(self):
        return '{}'.format(self.name)

class Album(models.Model):
    category = models.ForeignKey(Category,related_name="category",on_delete=models.CASCADE)

    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=250, unique=True)
    image = models.ImageField(upload_to="albumCover/%y/%m", blank=False)
    location = models.CharField(max_length=250,blank=True)
    show = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}'.format(self.name)

class AlbumImage(models.Model):
    album = models.ForeignKey(Album,related_name="album",on_delete=models.CASCADE)
    images = models.ImageField(upload_to="Images/%y/%m/%d",blank=False)

event/event/diaries/views.py
from django.shortcuts import render
from .models import Category,AlbumImage,Album

# Create your views here.
def home(request):
    template = "diaries/home.html"
    context = {}
    return render(request,template,context)


def album(request,slug_category=None):

    print("slug - > ",slug_category)

    category = Category.objects.all()
    albums = Album.objects.filter(show=True)


    if slug_category:
        cat = Category.objects.get(name=slug_category)
        albums = albums.filter(category=cat)
        print("inside album --> ",albums)
    print("outside album -->",albums)

    template = "diaries/album.html"
    context = {'category':category,'albums':albums}

    return render(request,template,context)

event/event/diaries/templates/diaries/album.html
{% extends "diaries/base.html" %} {% load static %} {% block title%}
Albums {% endblock title %} {% block style %}
<link href="{% static 'css/album.css' %}" rel="stylesheet" />

{% endblock style %} {% block content %}
<div class="bg"></div>
<div class="bg bg2"></div>
<div class="bg bg3"></div>
<div class="content">
  <div class="item_selector">
    <ul>
      <!-- <li><a href="#">All</a></li>
      <li><a href="#">Pre-wedding</a></li>
      <li><a href="#">Destination</a></li> -->

      <li><a href="{% url 'diaries:album' %}">All</a></li>
      {% for cat in category %}
      <li>
        <a href="{% url 'diaries:album' cat.slug %}">
          {{ cat.name }}</a
        >
      </li>
      {% endfor %}
    </ul>
  </div>
  <!-- image card -->
  <div class="wrapper">
    {% comment %} <div class="box">
      <a href="#">
        <img src="{% static 'img/797140.png' %}" />
        <div class="card_info">
          <p>Name</p>
          <p>Destination Name</p>
        </div>
      </a>
    </div> {% endcomment %}

    {% for items in albums  %}

        <div class="box">
      <a href="#">
        <img src="{{items.image.url}}" />
        <div class="card_info">
          <p>{{items.name}}</p>
          <p>{{items.location}}</p>
        </div>
      </a>
    </div>
    
    {% endfor %}

    
    <!-- <div class="box">
      <a href="#">
        <img src="{% static 'img/797140.png' %}" />
        <div class="card_info">
          <p>Name</p>
          <p>Destination Name</p>
        </div>
      </a>
    </div> -->
    <!-- <div class="box">
      <a href="#">
        <img src="{% static 'img/797140.png' %}" />
        <div class="card_info">
          <p>Name</p>
          <p>Destination Name</p>
        </div>
      </a>
    </div> -->
    <!-- wrapper end -->
  </div>

  {% endblock content %} {% block script %} {% endblock script %}
</div>

event/event/diaries/templates/diaries/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <link href="{% static 'css/header.css' %}" rel="stylesheet">
    <title>
    {% block title %}
    {% endblock title %}
    </title>
    
    {% block style %}
    
    {% endblock style %}
</head>
<body>
{% include "diaries/header.html" %}
{% block content %}

{% endblock content %}
{% block script %}

{% endblock script %}

</body>
</html>

event/event/diaries/templates/diaries/header.html
 <div class="header">
        <ul>
          <li><a href="{% url 'diaries:home' %}"">Home</a></li>
          <li><a href="{% url 'diaries:album' %}"">Album</a></li>
          <li><a href="#"">Services</a></li>
          <li><a href="#"">About Us</a></li>
        </ul>
</div>

event/event/diaries/templates/diaries/home.html
{% extends "diaries/base.html" %} {% load static %} {% block title%}
Home {% endblock title %} {% block style %}
<link href="{% static 'css/home.css' %}" rel="stylesheet" />

{% endblock style %} {% block content %}
<div class="wrapper">
  <div class="content">
    <div class="slides">
      <img
        id="slide-1"
        class=" img"
        src="{% static 'img/797140.png' %}"
      />

      <img
        id="slide-2"
        class=" img "
        src="{% static 'img/811143.jpg' %}"
      />

      <img
        id="slide-3"
        class=" img "
        src="{% static 'img/994295.png' %}"
      />
    </div>
  </div>
</div>

{% endblock content %} {% block script %}
<script src="{% static 'js/custom_slider.js' %}"></script>

{% endblock script %}